USE  mysql;
ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';
FLUSH PRIVILEGES;


CREATE DATABASE wordpress;
USE  ${MYSQL_DATABASE};
CREATE USER ${MYSQL_USER}@'%';
GRANT ALL PRIVILEGES ON wordpress.* TO ${MYSQL_USER}@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
FLUSH PRIVILEGES;