version: "3.7"

volumes:
  share_wordpress:
  share_db:

services:
  mariadb:
    platform: linux/amd64
    env_file: ./.env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    tty: true
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      intra:
        aliases:
          - mydb

  wordpress:
    depends_on:
      - mariadb
    platform: linux/amd64
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - share_wordpress:/share_wordpress
    expose:
      - "9000"
      - "3306"
    tty: true
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      DB_IP: mydb
    networks:
      intra:
        aliases:
          - mywordpress

  nginx:
    depends_on:
      - mariadb
      - wordpress
    platform: linux/amd64
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - share_wordpress:/share_wordpress
    expose:
      - "9000"
    restart: always
    ports:
      - 443:443
    tty: true
    networks:
      intra:
        aliases:
          - mynginx
    environment:
      - VIRTUAL_HOST=www.mjung.42.fr
      - VIRTUAL_PORT=3000

networks:
  intra:
    driver: bridge
