version: "3.7"

services:
  mariadb:
    platform: linux/amd64
    env_file: ./.env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - share_mysql:/var/lib/mysql
    restart: always
    tty: true
    expose:
      - "3306"
    networks:
      intra:
        aliases:
          - mydb
  wordpress:
    depends_on:
      - mariadb
    platform: linux/amd64
    env_file: ./.env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - share_wordpress:/share_wordpress
    expose:
      - "9000"
      - "3306"
    tty: true
    restart: always
    environment:
      DB_IP: mydb
    networks:
      intra:
        aliases:
          - mywordpress
  nginx:
    depends_on:
      - mariadb
      - wordpress
    platform: linux/amd64
    env_file: ./.env
    environment:
      WORDPRESS_IP: mywordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - share_wordpress:/share_wordpress
    expose:
      - "9000"
    restart: always
    ports:
      - 443:443
    tty: true
    networks:
      intra:
        aliases:
          - mynginx
volumes:
  share_wordpress:
    driver: local # docker
    driver_opts:
      type: "none" # 마운트 명령을 실행할 때 표시되는 마운트 지점에 연결된 물리적 디스크 파티션이 없음
      o: "bind" # -o : 드라이버별 옵션 설정, "bind" : 특정 디렉토리를 다른 디렉토리에 붙힐 수 있음
      device: "~/data/web" # 실제 host의 경로로 마운팅
  share_mysql:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "~/data/db"
networks:
  intra:
    driver: bridge
