version: "3.7"

services:
  mariadb:
    platform: linux/amd64
    env_file: ./.env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      # volumes:
      #   - dbdata:/var/lib/mysql
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      intra:
        aliases:
          - mydb

  wordpress:
    depends_on:
      - mariadb
    platform: linux/amd64
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - ~/mjung/data:/myPhp/data
    expose:
      - "9000"
      - "3306"
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      intra:
        aliases:
          - mywordpress

  nginx:
    depends_on:
      - mariadb
      - wordpress
    platform: linux/amd64
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - ~/mjung/data:/myPhp/data
    expose:
      - "9000"
      - "3306"
    restart: always
    ports:
      - 443:443
    networks:
      intra:
        aliases:
          - mynginx

networks:
  intra:
    driver: bridge
