version: "3.7"

services:
  mariadb:
    platform: linux/amd64
    env_file: ./.env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    # volumes:
    #   - share_mysql:/share_mysql
    restart: always
    tty: true
    expose:
      - "3306"
    networks:
      intra:
        aliases:
          - mydb

  wordpress:
    depends_on:
      - mariadb
    platform: linux/amd64
    env_file: ./.env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      # - share_wordpress
      - ~/mjung/data/web/wordpress:/share_wordpress
    expose:
      - "9000"
      - "3306"
    tty: true
    restart: always
    environment:
      DB_IP: mydb
    networks:
      intra:
        aliases:
          - mywordpress

  nginx:
    depends_on:
      - mariadb
      - wordpress
    platform: linux/amd64
    env_file: ./.env
    environment:
      WORDPRESS_IP: mywordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      # - share_wordpress
      - ~/mjung/data/web/wordpress:/share_wordpress
    expose:
      - "9000"
    restart: always
    ports:
      - 443:443
    tty: true
    networks:
      intra:
        aliases:
          - mynginx
    # dns_search:
    #   - dc1.example.com
    #   - dc2.example.com
volumes:
  share_wordpress:
  # share_wordpress: ~/mjung/data/wordpress

networks:
  intra:
    driver: bridge
